### ISSUE TITLE
add getRegisteredDelegates function

### ISSUE THREAD

**Issue by Moustikitos** [ArkEcosystem/ark-api#2]
Hi,

working on python API, i am building a wallet object with usefull functions.

I need to find all registered deletages (even those ranked more than 51).

I can find all Peers (network nodes), i can get the 51 lucky username but I did'nt find a way (via the API) to get the unlucky ones.

Thanks

**Comment by Doweig** [comment]
What about this API?
https://github.com/ArkEcosystem/ark-api#get-delegates

**Comment by Moustikitos** [comment]
Ok i cacth the offset option

Thanks
